- name: Testing Connections
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

- name: Install Docker
  hosts: Test
  roles:
    -  geerlingguy.pip
    -  geerlingguy.docker
  vars:
   docker_users:
    - root
   pip_install_packages:
    - name:
        - packaging
        - docker
  become: true
