# SPDX-License-Identifier: MIT-0
---
# tasks file for caddy
- name: Install Caddy (Debian)
  ansible.builtin.include_tasks: packages-deb.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install Caddy (Fedora)
  ansible.builtin.include_tasks: packages-rh.yml
  when: ansible_facts['os_family'] == "RedHat"
  